### ISSUE TITLE
OWFaceDetector: doesn't work with Neighbors

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/lookalike-demo#6]
Face Detector adds another meta attribute to domain, which then crashes Neighbors. Perhaps replace the old image with new path to avoid having two different domains.

**Comment by markotoplak** [comment]
Why solve it this way? Perhaps as a quick fix, bit this looks like a Neighbors problem. We should probably fix it to ignore metas or to even try converting between domain?

**Comment by ajdapretnar** [comment]
Fixed via https://github.com/biolab/orange3/pull/3555.
